Cleaning up tekton tasks

diff --git a/roles/pipeline/templates/tasks.yml.j2 b/roles/pipeline/templates/tasks.yml.j2
--- a/roles/pipeline/templates/tasks.yml.j2
+++ b/roles/pipeline/templates/tasks.yml.j2
@@ -176,113 +176,105 @@
         - name: source
           type: git
     steps:
-    - image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'
-      name: extract-git-rev
-      resources: {}
-      script: >
-        #!/bin/sh
+      - name: extract-git-rev
+        image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'
+        script: >
+          #!/bin/sh
 
-        set -e -o pipefail
+          set -e -o pipefail
 
-        # get git sha
+          # get git sha
 
-        git rev-parse --verify --short HEAD | tee $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt
-      workingDir: $(inputs.resources.source.path)
-    - args:
-        - >-
-          echo "Creating new build config"  &&
+          git rev-parse --verify --short HEAD | tee
+          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt
+        workingDir: $(inputs.resources.source.path)
+      - name: create-build-config
+        image: 'quay.io/openshift/origin-cli:latest'
+        script: >
+          #!/bin/sh
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)   && 
+          set -e -o pipefail
 
-          echo "Extracted git revision from previous step $GITSHA" &&
+          echo "Creating new build config"  
+
+          GITSHA=$(cat
+          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)  
+
+
+          echo "Extracted git revision from previous step $GITSHA" 
 
           # This allows the new build to be created whether it exists or not
 
-          oc new-build -o yaml --name=$(inputs.params.app_name)
-          --image-stream=jboss-eap72-openshift:1.1  --binary=true -n
-          $(inputs.params.dev_project) | oc apply -n
-          $(inputs.params.dev_project) -f - 
-      command:
-        - /bin/sh
-        - '-c'
-      image: 'quay.io/openshift/origin-cli:latest'
-      name: create-build-config
-      resources: {}
-    - args:
-        - >-
-          echo "Start the openshift build"  && 
+          oc new-build -o yaml --name=$(inputs.params.app_name) --image-stream=jboss-eap72-openshift:1.1  --binary=true -n
+          $(inputs.params.dev_project) | oc apply -n $(inputs.params.dev_project) -f - 
+      - name: build-app-image
+        image: 'quay.io/openshift/origin-cli:latest'    
+        script: >
+          #!/bin/sh
+
+          set -e -o pipefail
+
+          echo "Start the openshift build"  
 
 
-          rm -rf $(inputs.resources.source.path)/oc-build && mkdir -p
-          $(inputs.resources.source.path)/oc-build/deployments && 
+          rm -rf $(inputs.resources.source.path)/oc-build && mkdir -p $(inputs.resources.source.path)/oc-build/deployments 
 
 
-          cp
-          $(workspaces.maven-repo.path)/org/jboss/quickstarts/eap/jboss-tasks-rs/7.0.0-SNAPSHOT/jboss-tasks-rs-7.0.0-SNAPSHOT.war
-          $(inputs.resources.source.path)/oc-build/deployments/ROOT.war && 
+          cp $(workspaces.maven-repo.path)/org/jboss/quickstarts/eap/jboss-tasks-rs/7.0.0-SNAPSHOT/jboss-tasks-rs-7.0.0-SNAPSHOT.war
+          $(inputs.resources.source.path)/oc-build/deployments/ROOT.war 
 
 
-          oc start-build $(inputs.params.app_name)
-          --from-dir=$(inputs.resources.source.path)/oc-build -n
-          $(inputs.params.dev_project) --wait=true && 
+          oc start-build $(inputs.params.app_name) --from-dir=$(inputs.resources.source.path)/oc-build -n   $(inputs.params.dev_project) --wait=true 
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)  &&
+          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
 
-          oc tag $(inputs.params.app_name):latest
-          $(inputs.params.app_name):$GITSHA -n $(inputs.params.dev_project)
-          && 
 
-          echo "Successfully created container image
-          $(inputs.params.dev_project)/$(inputs.params.app_name):$GITSHA"
-      command:
-        - /bin/sh
-        - '-c'
-      image: 'quay.io/openshift/origin-cli:latest'
-      name: build-app-image
-      resources: {}
-    - args:
-        - >-
-          echo "Create new app from tasks image stream in
-          $(inputs.params.dev_project) project"   &&
+          oc tag $(inputs.params.app_name):latest  $(inputs.params.app_name):$GITSHA -n $(inputs.params.dev_project) 
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)  &&
+          echo "Successfully created container image $(inputs.params.dev_project)/$(inputs.params.app_name):$GITSHA"
+      - name: deploy-app-from-image
+        image: 'quay.io/openshift/origin-cli:latest'            
+        script: >
+          #!/bin/sh
+
+          set -e -o pipefail
+
+          echo "Create new app from tasks image stream in $(inputs.params.dev_project) project"   
+
+          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
 
           oc new-app --image-stream=$(inputs.params.app_name):$GITSHA -n
-          $(inputs.params.dev_project) --as-deployment-config=true -o yaml | oc
-          apply -n $(inputs.params.dev_project)  -f - && 
-
-          oc delete route $(inputs.params.app_name) -n
-          $(inputs.params.dev_project) || oc expose svc
-          $(inputs.params.app_name) -n $(inputs.params.dev_project)  && 
+          $(inputs.params.dev_project) --as-deployment-config=true -o yaml | oc apply -n $(inputs.params.dev_project)  -f - 
 
           echo "Setting manual triggers on deployment $(inputs.params.app_name)"
-          && 
 
-          oc set triggers dc/$(inputs.params.app_name) --manual=true -n
-          $(inputs.params.dev_project) 
-      command:
-        - /bin/sh
-        - '-c'
-      image: 'quay.io/openshift/origin-cli:latest'
-      name: deploy-app-from-image
-      resources: {}
+          oc set triggers dc/$(inputs.params.app_name) --manual=true -n  $(inputs.params.dev_project) 
 
-    - name: announce-success
-      image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'
-      resources: {}
-      script: >
-        #!/bin/sh
+          if ! oc get route/$(inputs.params.app_name) -n $(inputs.params.dev_project) ; then
 
-        set -e -o pipefail
+            oc expose svc $(inputs.params.app_name) -n $(inputs.params.dev_project) || echo "Failed to create route for $(inputs.params.app_name)"
+
+          fi
+            
+          oc rollout latest dc/$(inputs.params.app_name) -n  $(inputs.params.dev_project)
+
+      - name: announce-success
+        image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'      
+        script: >
+          #!/bin/sh
+
+          set -e -o pipefail
 
 
-        GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)  &&
-        
-        echo "Successfully build application $(inputs.params.app_name)"
+          GITSHA=$(cat
+          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
+          &&
 
-        echo "After testing the app, run the deploy-app-to-stage pipeline with $GITSHA as the app_version parameter"
+          echo "Successfully build application $(inputs.params.app_name)"
 
-      workingDir: $(inputs.resources.source.path)
+          echo "After testing the app, run the deploy-app-to-stage pipeline with
+          $GITSHA as the app_version parameter"
+        workingDir: $(inputs.resources.source.path)
     workspaces:
       - name: maven-repo
 
@@ -310,50 +302,49 @@
           name: app_revision
           type: string
     steps:
-    - args:
-        - >-
-          echo "Tagging image stream in 
-          $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)"
-          &&
+    - name: cleanup-stage-project
+      script: >
+        #!/bin/sh
 
-          oc tag
-          $(inputs.params.dev_project)/$(inputs.params.app_name):$(inputs.params.app_revision)
-          $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)
-          && 
+        set -e -o pipefail
 
-          if oc get dc/$(inputs.params.app_name) -n
-          $(inputs.params.stage_project) ; then echo "Tasks dc exists, deleting
-          resources " && oc delete dc/tasks svc/tasks route/tasks -n $(inputs.params.stage_project) || echo
-          "Some resources didn't clean up as expected"; else echo "Tasks dc doesn't exist, no
-          cleanup needed"; fi
-      command:
-        - /bin/sh
-        - '-c'
+        echo "Tagging image stream in 
+        $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)"          
+
+        oc tag
+        $(inputs.params.dev_project)/$(inputs.params.app_name):$(inputs.params.app_revision)
+        $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)          
+
+        if oc get dc/$(inputs.params.app_name) -n $(inputs.params.stage_project); then
+
+          echo "Tasks dc exists, cleaning up resources " 
+          
+          oc delete dc/$(inputs.params.app_name) svc/$(inputs.params.app_name) route/$(inputs.params.app_name) 
+          -n $(inputs.params.stage_project) || echo "Some resources didn't clean up as expected"; 
+
+        fi
+
       image: 'quay.io/openshift/origin-cli:latest'
-      name: cleanup-stage-project
-      resources: {}
-    - args:
-        - >-
-          echo "Deploying new version into $(inputs.params.stage_project)
-          project "  &&
 
-          oc new-app
-          --image-stream=$(inputs.params.app_name):$(inputs.params.app_revision)
-          -n $(inputs.params.stage_project) --as-deployment-config=true -o yaml
-          | oc apply -n $(inputs.params.stage_project)  -f -  && 
+    - name: deploy-new-version-to-stage
+      script: >
+        #!/bin/sh
 
-          if oc get route $(inputs.params.app_name) -n
-          $(inputs.params.stage_project); then echo "Cleaning up route" && oc
-          delete route $(inputs.params.app_name) -n
-          $(inputs.params.stage_project) ; else echo "Route didn't require clean
-          up"; fi && 
+        set -e -o pipefail
 
-          oc expose svc $(inputs.params.app_name) -n
-          $(inputs.params.stage_project) 
-      command:
-        - /bin/sh
-        - '-c'
+        echo "Deploying new version into $(inputs.params.stage_project)  project "  
+
+        oc new-app --image-stream=$(inputs.params.app_name):$(inputs.params.app_revision) -n $(inputs.params.stage_project) 
+        --as-deployment-config=true -o yaml  | oc apply -n $(inputs.params.stage_project)  -f -   
+
+
+        if ! oc get route/$(inputs.params.app_name) -n $(inputs.params.stage_project) ; then
+          
+          echo "Route not found, creating a new one" 
+
+          oc expose svc $(inputs.params.app_name) -n  $(inputs.params.stage_project); 
+
+        fi  
+
       image: 'quay.io/openshift/origin-cli:latest'
-      name: deploy-new-version-to-stage
-      resources: {}
 {% endfor %}
