Updated tasks to use params instead of inputs.params

diff --git a/roles/pipeline/templates/tasks.yml.j2 b/roles/pipeline/templates/tasks.yml.j2
--- a/roles/pipeline/templates/tasks.yml.j2
+++ b/roles/pipeline/templates/tasks.yml.j2
@@ -36,13 +36,13 @@
     steps:
     - args:
       - |-
-        echo "MAVEN_CLEAR_REPO=$(inputs.params.MAVEN_CLEAR_REPO)" > env-file
+        echo "MAVEN_CLEAR_REPO=$(params.MAVEN_CLEAR_REPO)" > env-file
 
-        [[ '$(inputs.params.MAVEN_ARGS_APPEND)' != "" ]] &&
-          echo "MAVEN_ARGS_APPEND=$(inputs.params.MAVEN_ARGS_APPEND)" >> env-file
+        [[ '$(params.MAVEN_ARGS_APPEND)' != "" ]] &&
+          echo "MAVEN_ARGS_APPEND=$(params.MAVEN_ARGS_APPEND)" >> env-file
 
-        [[ '$(inputs.params.MAVEN_MIRROR_URL)' != "" ]] &&
-          echo "MAVEN_MIRROR_URL=$(inputs.params.MAVEN_MIRROR_URL)" >> env-file
+        [[ '$(params.MAVEN_MIRROR_URL)' != "" ]] &&
+          echo "MAVEN_MIRROR_URL=$(params.MAVEN_MIRROR_URL)" >> env-file
 
         echo "Generated Env file"
         echo "------------------------------"
@@ -61,7 +61,7 @@
     - command:
       - s2i
       - build
-      - $(inputs.params.PATH_CONTEXT)
+      - $(params.PATH_CONTEXT)
       # This could also use something like image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/jboss-eap72-openshift:1.1
       # from the built in registry
       - image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/jboss-eap72-openshift:1.1
@@ -83,7 +83,7 @@
     - command:
       - buildah
       - bud
-      - --tls-verify=$(inputs.params.TLSVERIFY)
+      - --tls-verify=$(params.TLSVERIFY)
       - --layers
       - -f
       - /gen-source/Dockerfile.gen
@@ -104,7 +104,7 @@
     - command:
       - buildah
       - push
-      - --tls-verify=$(inputs.params.TLSVERIFY)
+      - --tls-verify=$(params.TLSVERIFY)
       - $(outputs.resources.image.url)
       - docker://$(outputs.resources.image.url)
       image: quay.io/buildah/stable
@@ -145,8 +145,8 @@
           type: git
     steps:
       - args:
-          - $(inputs.params.GOALS)
-          - '-s$(inputs.resources.source.path)/$(inputs.params.settings-path)'
+          - $(params.GOALS)
+          - '-s$(inputs.resources.source.path)/$(params.settings-path)'
         command:
           - /usr/bin/mvn
         image: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
@@ -189,7 +189,7 @@
           # get git sha
 
           git rev-parse --verify --short HEAD | tee
-          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt
+          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt
         workingDir: $(inputs.resources.source.path)
       - name: create-build-config
         image: 'quay.io/openshift/origin-cli:latest'
@@ -201,15 +201,15 @@
           echo "Creating new build config"  
 
           GITSHA=$(cat
-          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt)  
+          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)  
 
 
           echo "Extracted git revision from previous step $GITSHA" 
 
           # This allows the new build to be created whether it exists or not
 
-          oc new-build -o yaml --name=$(inputs.params.app_name) --image-stream=jboss-eap72-openshift:1.1  --binary=true -n
-          $(inputs.params.dev_project) | oc apply -n $(inputs.params.dev_project) -f - 
+          oc new-build -o yaml --name=$(params.app_name) --image-stream=jboss-eap72-openshift:1.1  --binary=true -n
+          $(params.dev_project) | oc apply -n $(params.dev_project) -f - 
       - name: build-app-image
         image: 'quay.io/openshift/origin-cli:latest'    
         script: >
@@ -223,17 +223,17 @@
           rm -rf $(inputs.resources.source.path)/oc-build && mkdir -p $(inputs.resources.source.path)/oc-build/deployments 
 
 
-          cp $(workspaces.maven-repo.path)/$(inputs.params.artifact_path) $(inputs.resources.source.path)/oc-build/deployments/ROOT.war 
+          cp $(workspaces.maven-repo.path)/$(params.artifact_path) $(inputs.resources.source.path)/oc-build/deployments/ROOT.war 
 
 
-          oc start-build $(inputs.params.app_name) --from-dir=$(inputs.resources.source.path)/oc-build -n   $(inputs.params.dev_project) --wait=true 
+          oc start-build $(params.app_name) --from-dir=$(inputs.resources.source.path)/oc-build -n   $(params.dev_project) --wait=true 
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
+          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
 
 
-          oc tag $(inputs.params.app_name):latest  $(inputs.params.app_name):$GITSHA -n $(inputs.params.dev_project) 
+          oc tag $(params.app_name):latest  $(params.app_name):$GITSHA -n $(params.dev_project) 
 
-          echo "Successfully created container image $(inputs.params.dev_project)/$(inputs.params.app_name):$GITSHA"
+          echo "Successfully created container image $(params.dev_project)/$(params.app_name):$GITSHA"
       - name: deploy-app-from-image
         image: 'quay.io/openshift/origin-cli:latest'            
         script: >
@@ -241,24 +241,24 @@
 
           set -e -o pipefail
 
-          echo "Create new app from tasks image stream in $(inputs.params.dev_project) project"   
+          echo "Create new app from tasks image stream in $(params.dev_project) project"   
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
+          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
 
-          oc new-app --image-stream=$(inputs.params.app_name):$GITSHA -n
-          $(inputs.params.dev_project) --as-deployment-config=true -o yaml | oc apply -n $(inputs.params.dev_project)  -f - 
+          oc new-app --image-stream=$(params.app_name):$GITSHA -n
+          $(params.dev_project) --as-deployment-config=true -o yaml | oc apply -n $(params.dev_project)  -f - 
 
-          echo "Setting manual triggers on deployment $(inputs.params.app_name)"
+          echo "Setting manual triggers on deployment $(params.app_name)"
 
-          oc set triggers dc/$(inputs.params.app_name) --manual=true -n  $(inputs.params.dev_project) 
+          oc set triggers dc/$(params.app_name) --manual=true -n  $(params.dev_project) 
 
-          if ! oc get route/$(inputs.params.app_name) -n $(inputs.params.dev_project) ; then
+          if ! oc get route/$(params.app_name) -n $(params.dev_project) ; then
 
-            oc expose svc $(inputs.params.app_name) -n $(inputs.params.dev_project) || echo "Failed to create route for $(inputs.params.app_name)"
+            oc expose svc $(params.app_name) -n $(params.dev_project) || echo "Failed to create route for $(params.app_name)"
 
           fi
             
-          oc rollout latest dc/$(inputs.params.app_name) -n  $(inputs.params.dev_project)
+          oc rollout latest dc/$(params.app_name) -n  $(params.dev_project)
 
       - name: announce-success
         image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'      
@@ -269,10 +269,10 @@
 
 
           GITSHA=$(cat
-          $(inputs.resources.source.path)/$(inputs.params.app_name)-gitsha.txt) 
+          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
           &&
 
-          echo "Successfully build application $(inputs.params.app_name)"
+          echo "Successfully build application $(params.app_name)"
 
           echo "After testing the app, run the deploy-app-to-stage pipeline with
           $GITSHA as the app_version parameter"
@@ -310,17 +310,17 @@
         set -e -o pipefail
 
         echo "Tagging image stream in 
-        $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)"          
+        $(params.stage_project)/$(params.app_name):$(params.app_revision)"          
 
         oc tag
-        $(inputs.params.dev_project)/$(inputs.params.app_name):$(inputs.params.app_revision)
-        $(inputs.params.stage_project)/$(inputs.params.app_name):$(inputs.params.app_revision)          
+        $(params.dev_project)/$(params.app_name):$(params.app_revision)
+        $(params.stage_project)/$(params.app_name):$(params.app_revision)          
 
-        if oc get dc/$(inputs.params.app_name) -n $(inputs.params.stage_project); then
+        if oc get dc/$(params.app_name) -n $(params.stage_project); then
 
           echo "Tasks dc exists, cleaning up resources " 
           
-          oc delete -n $(inputs.params.stage_project) dc/$(inputs.params.app_name) svc/$(inputs.params.app_name) route/$(inputs.params.app_name) || echo "Some resources didn't clean up as expected"; 
+          oc delete -n $(params.stage_project) dc/$(params.app_name) svc/$(params.app_name) route/$(params.app_name) || echo "Some resources didn't clean up as expected"; 
 
         fi
 
@@ -332,17 +332,17 @@
 
         set -e -o pipefail
 
-        echo "Deploying new version into $(inputs.params.stage_project)  project "  
+        echo "Deploying new version into $(params.stage_project)  project "  
 
-        oc new-app --image-stream=$(inputs.params.app_name):$(inputs.params.app_revision) -n $(inputs.params.stage_project) 
-        --as-deployment-config=true -o yaml  | oc apply -n $(inputs.params.stage_project)  -f -   
+        oc new-app --image-stream=$(params.app_name):$(params.app_revision) -n $(params.stage_project) 
+        --as-deployment-config=true -o yaml  | oc apply -n $(params.stage_project)  -f -   
 
 
-        if ! oc get route/$(inputs.params.app_name) -n $(inputs.params.stage_project) ; then
+        if ! oc get route/$(params.app_name) -n $(params.stage_project) ; then
           
           echo "Route not found, creating a new one" 
 
-          oc expose svc $(inputs.params.app_name) -n  $(inputs.params.stage_project); 
+          oc expose svc $(params.app_name) -n  $(params.stage_project); 
 
         fi  
 
