fix acme.sh container problems

diff --git a/roles/cluster-adjuster/tasks/letsencrypt.yml b/roles/cluster-adjuster/tasks/letsencrypt.yml
--- a/roles/cluster-adjuster/tasks/letsencrypt.yml
+++ b/roles/cluster-adjuster/tasks/letsencrypt.yml
@@ -20,8 +20,7 @@
     else
         echo ok
     fi
-
-    abort=0 # try 5 times to make sure we've got the right endpoints
+    abort=0 # try 5 times to make sure we have the right endpoints
     while ! api_endpoint=$($oc whoami --show-server); do
         sleep 5
         ((abort++))
@@ -40,19 +39,26 @@
             exit 1
         fi
     done
-
-    acme='{{ _tmp_parent }}/acme.sh/acme.sh'
+    echo "api_endpoint: $api_endpoint"
+    echo "wildcard_endpoint: $wildcard_endpoint"
+    acme='{{ _tmp_parent }}/acme.sh/acme.sh --home {{ _tmp_parent }}/acme.sh/home'
     acme_args=(-d "$api_endpoint" -d "$wildcard_endpoint" --dns dns_aws
         --cert-file '{{ certificate_path }}/cert.pem'
         --key-file '{{ certificate_path }}/key.pem'
         --ca-file '{{ certificate_path }}/ca.pem'
         --fullchain-file '{{ certificate_path }}/fullchain.pem'
     )
-    if $acme --list | grep -qF "$api_endpoint" && $acme --list | grep -qF "$wildcard_endpoint"; then # there is a cert issued already
-        if ! $acme --install-cert "${acme_args[@]}"; then # we couldn't install it, try to renew
+    if $acme --list | grep -qF "$api_endpoint" && $acme --list | grep -qF "$wildcard_endpoint"; then
+        echo "There appears to be a cert issued already."
+        if ! $acme --install-cert "${acme_args[@]}"; then
+            echo "Unable to install the certificate. Attempting to renew."
             $acme --renew "${acme_args[@]}" --force || exit 1
+            echo "Certificate renewed!"
+        else
+            echo "Certificate installed!"
         fi
-    else # no certs issued, request them
+    else
+        echo "Unable to identify any issued certificates. Requesting them..."
         $acme --issue "${acme_args[@]}" || exit 1
     fi
   args:
